# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{teambox-things-sync}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Arkadiusz Holko"]
  s.date = %q{2010-09-15}
  s.default_executable = %q{teambox-things-sync}
  s.email = %q{fastred@fastred.org}
  s.executables = ["teambox-things-sync"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/teambox-things-sync",
     "lib/teambox-things-sync.rb",
     "lib/teambox-things-sync/base.rb",
     "lib/teambox-things-sync/command.rb",
     "lib/teambox-things-sync/config_store.rb",
     "lib/teambox-things-sync/task_list_cache.rb",
     "spec/spec_helper.rb",
     "spec/teambox-things-sync/base_spec.rb",
     "spec/teambox-things-sync/task_list_cache_spec.rb",
     "spec/teambox-things-sync_spec.rb",
     "teambox-things-sync.gemspec"
  ]
  s.homepage = %q{http://github.com/fastred/teambox-things-sync}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Simple ruby app for Teambox and Things.app syncing}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/teambox-things-sync/base_spec.rb",
     "spec/teambox-things-sync/task_list_cache_spec.rb",
     "spec/teambox-things-sync_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.20"])
      s.add_runtime_dependency(%q<teambox-client>, ["= 0.2.0"])
      s.add_runtime_dependency(%q<things-client>, ["= 0.2.4"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.20"])
      s.add_dependency(%q<teambox-client>, ["= 0.2.0"])
      s.add_dependency(%q<things-client>, ["= 0.2.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.20"])
    s.add_dependency(%q<teambox-client>, ["= 0.2.0"])
    s.add_dependency(%q<things-client>, ["= 0.2.4"])
  end
end

